name: Tests
on:
  pull_request: { branches: ['*'] }
  push: { branches: [master] }
permissions: { contents: read }
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew check -Dgeb.env=firefoxHeadless