grails:
    profile: web
    codegen:
        defaultPackage: pingcrm
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    controllers:
        upload:
            maxFileSize: 524288
            maxRequestSize: 1048576
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'

# Uncomment for enabling h2 database console (also look at grails.plugin.springsecurity below)
# spring.h2.console.enabled: true

management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
    jdbc:
        time_zone: UTC
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;TIME ZONE=UTC
            # Uncomment the next two lines to log sql queries (also look in logback.xml)
            #logSql: true
            #formatSql: true
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;TIME ZONE=UTC
    production:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;TIME ZONE=UTC
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
grails:
    plugin:
        springsecurity:
            auth.loginFormUrl: /login
            authority.className: pingcrm.auth.Role
            userLookup:
                userDomainClassName: pingcrm.User
                authorityJoinClassName: pingcrm.auth.UserRole
            rememberMe:
                cookieName: pingcrm-remember-me
                key: this-should-be-unique-per-application
                sameSite: Lax

            controllerAnnotations.staticRules:
                - pattern: '/'
                  access: ['permitAll']
                - pattern: '/error'
                  access: ['permitAll']
                - pattern: '/**/favicon.ico'
                  access: ['permitAll']
                - pattern: '/static/**'
                  access: ['permitAll']
                # Uncomment to enable access to h2 database console (also look at spring.h2.console.enabled above)
                # - pattern: '/h2-console/**'
                #   access: ['permitAll']
            filterChain.chainMap:
                - pattern: '/**/favicon.ico'
                  filters: 'none'
                - pattern: '/static/**'
                  filters: 'none'
                # Uncomment to enable access to h2 database console (also look at spring.h2.console.enabled above)
                # - pattern: '/h2-console/**'
                #   filters: 'none'
                - pattern: '/**'
                  filters: 'JOINED_FILTERS'
---
server:
    servlet:
        session:
            cookie:
                same-site: Lax
    forward-headers-strategy: NATIVE
    tomcat:
        max-swallow-size: 1048576
        max-post-size: 1048576
        redirect-context-root: false
---
inertia:
    ssr:
        enabled: true
        # The default url should preferably be picked up from Inertia Plugins plugin.yml,
        # but sadly is not working when using Micronaut ConfigurationProperties, so I'm setting it here as well.
        # https://github.com/grails/grails-core/issues/11767
        # https://github.com/grails/grails-core/pull/11828
        url: 'http://localhost:13714/render'
